---
title: "Perdidas trab clase"
author: "Andres gonzalez"
date: "1/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Ejercicios en clase

## Deducibles

### 4.1 Deducibles de franquicia

```{r}
1-(1-((2000/2500)^3))

x <- 0:5000
fpareto <- dpareto(x, shape = 3, scale = 2000)
plot(x,fpareto)

```

```{r}
n <- 100000
pareto_aleatorio <- rpareto(n, shape = 3, scale = 2000)
hist(pareto_aleatorio, freq = FALSE, breaks = 1000)

```

```{r}
idx <- pareto_aleatorio > 500
YL <- numeric(n)
YL[idx] <- pareto_aleatorio[idx]
YL[!idx] <- 0
hYL <- hist(YL, breaks = 1000, freq = FALSE, xlim = c(0, 5000))
```

```{r}
x <- 1:5000
fYL <- 3 * (2000)^3 / (2000 + x)^4
plot(1:5000, fYL)
points(hYL$mids, hYL$density, col = "red", type = "h")


```
```{R}
YP <- NA
YP[idx] <- pareto_aleatorio[idx]
hYP <- hist(YP, breaks = 5000, freq = FALSE)
```

```{r}
x <- 1:5000
fYP <- 3*(2500)^3/(x+2000)^4
plot(1:5000, fYP)
points(hYP$mids, hYP$density, col = "red", type = "h")

```
```{r}
plot(1:5000, fYP, type = "l", col = "blue")
lines(1:5000, fYL, col = "red")
```

### 4.3 Efecto de la inflacion

```{r}
k<-500/1.1
r<- 0.1

costo.perdida <- (1+r)*( (2000/2) - ((2000/2)*(1-( (2000)^2/((2000+k)^2))  )) )

costo.pago <- costo.perdida / ((2000/(k+2000))^3)

costo.pago

```
### 4.3.5 Limite de poliza
```{r}
n <- 100000
pareto_aleatorio <- rpareto(n, shape = 3, scale = 2000)
hist(pareto_aleatorio, freq = FALSE, breaks = 1000)

```

```{r}
idx <- pareto_aleatorio < 3000
YL <- numeric(n)
YL[idx] <- pareto_aleatorio[idx]
YL[!idx] <- 3000
hYL <- hist(YL, breaks = 1000, freq = FALSE, xlim = c(0, 5000))
```

```{r}
x <- 1:5000
fYL <- 3 * (2000)^3 / (2000 + x)^4
plot(1:5000, fYL)
points(hYL$mids, hYL$density, col = "red", type = "h")
```

#### Valor esperado con inflacion y sin inflacion, limite de poliza

```{r}
k <- 3000/1.1
esp.yu.infl <- (1.1)*(1000 *(1-((2000/(2000+k))^2)) )
esp.yu <- 1000*(1-( (2000/5000)^2  ))

esp.yu.infl
esp.yu
```

### 4.4 Generalizacion de modificaciones

```{r}
#FALTA


```

### 4.5 Impacto deducible frecuencia de reclamos

```{r}


```

## 5.4 Impacto de las pólizas individuales al modelo agregado

### Ejercicio 5.5

```{r}

N <- read.csv("cap04_ejercicio_5_5_N.csv")
X <- read.csv("cap04_ejercicio_5_5_X.csv")



#Ajustar dist de la N

nn <- data.frame(table(N$x))



n <- 1:9 * nn$Freq[2:length(nn$Var1)] / nn$Freq[1:(length(nn$Var1) -1 )]

plot(n)

n_techo <- data.frame(i = 1:length(n),n)


modelo <- lm(n_techo$n ~ n_techo$i)

a <- modelo$coefficients[1]
b <- modelo$coefficients[2]

```

## Modelo de riesgo individual

### Ejercicio 5.6

```{r}
tabla9.16 <- read.csv(text = "Empleado,Edad,Genero,Beneficio,Mortalidad
1,20,M ,15000,0.00149
2,23,M ,16000,0.00142
3,27,M ,20000,0.00128
4,30,M ,28000,0.00122
5,31,M ,31000,0.00123
6,46,M ,18000,0.00353
7,47,M ,26000,0.00394
8,49,M ,24000,0.00484
9,64,M ,60000,0.02182
10,17,F ,14000,0.0005
11,22,F ,17000,0.0005
12,26,F ,19000,0.00054
13,37,F ,30000,0.00103
14,55,F ,55000,0.00479
")

mu_S <- tabla9.16 %>%
  mutate(prod = Beneficio * Mortalidad) %>%
  summarise(sum(prod))
mu_S

var_S <- tabla9.16 %>%
  mutate(prod = Beneficio^2 * Mortalidad * (1 - Mortalidad)) %>%
  summarise(sum(prod))
var_S

mu_s <- mu_S$`sum(prod)`[1] / 1000
sd_s <- sqrt( var_S$`sum(prod)`[1] / (1000*1000) )


pnorm(mu_s, mean=mu_s, sd = sd_s, lower.tail = F)

plnorm(mu_s,meanlog = -0.89516, sdlog = 1.79733 , lower.tail = F)

#aumento del 45%

pnorm(mu_s * 1.45 , mean=mu_s, sd=sd_s, lower.tail = F)

plnorm(mu_s * 1.45, mean=-0.89516, sd=1.79733,lower.tail = F)


```